version: '3.7'

services:
  mysql-db:
    build: .
    command: mysql
    container_name: mysql-db
    hostname: mysql-db
    ports:
      - 3306:3306
      - 33060:33060

    restart: always
    volumes:
      - ./databases:/usr/local
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
